Wedding Halls/eventhalls/eventhalls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('venues/', include('venues.urls'), name='venues-app'),
    path('customers/', include('customers.urls'), name='customers-app'),
    path('', include('main.urls')),
    path('messages/', include('messages_app.urls'), name='messages-app'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Wedding Halls/eventhalls/main/urls.py
from django.urls import include, path
from . import views



urlpatterns = [
    path('', views.main, name = 'main'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact-us/', views.contact_us, name='contact-us')
]

Wedding Halls/eventhalls/venues/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'venues'

urlpatterns = [
    path('', views.home, name='venues_home'),
    path('general-information/', views.general_information, name='general-information'),
    path('edit-general-information/', views.edit_general_information, name='edit-general-information'),
    path('prewedding-preparation/', views.prewedding_prep, name='prewedding-prep'),
    path('edit-prewedding-preparation/', views.edit_prewedding_prep, name='edit-prewedding-prep'),
    path('food-and-drink/', views.food_and_drink, name='food-and-drink'),
    path('drink-options/', views.add_drink_options, name='drink-options'),
    path('dietary-option/', views.dietary_options, name='dietary-option'),
    path('menu-options/', views.add_food_option, name='food-option'),
    path('current-menu-pricing/', views.show_food_pricing, name='current-menu-pricing'),
    path('edit-dietary-option/', views.edit_dietary_options, name='edit-dietary-option'),
    path('ceremony-and-reception/', views.ceremony_and_reception, name='ceremony-and-reception'),
    path('edit-ceremony-and-reception/', views.edit_ceremony_and_reception, name='edit-ceremony-and-reception'),
    path('staffing/', views.staffing, name='staffing'),
    path('accommodations-and-parking/', views.accommodations_and_parking, name='accommodations-and-parking'),
    path('edit-accommodations-and-parking/', views.edit_accommodations_and_parking, name='edit-accommodations-and-parking'),
    path('payment-options/', views.payment_options, name='payment-options'),
    path('edit-payment-options/', views.edit_payment_options, name='edit-payment-options'),
    path('contact-info/', views.contact_info, name='contact-info'),
    path('edit-contact-info/', views.edit_contact_info, name='edit-contact-info'),
    path('decorations/', views.decorations, name='decorations'),
    path('edit-decorations/', views.edit_decorations, name='edit-decorations'),
    path('additional-information/', views.additional_information, name='additional-information'),
    path('edit-additional-information/', views.edit_additional_information, name='edit-additional-information'),
    path('venue-pictures/', views.venue_images, name='venue-images'),
    path('delete-venue-pictures/<int:id>', views.delete_image, name='delete-image'),
    path('current-drink-pricing/', views.show_drink_pricing, name='current-drink-pricing'),
    path('wedding-cake/', views.wedding_cake, name='wedding-cake'),
    path('current-wedding-cake-details/', views.show_wedding_cake, name='current-cake-details'),
    path('photography-and-videography/', views.photography, name='photography'),
    path('edit-photography-and-videography/', views.edit_photography, name='edit-photography')
]

Wedding Halls/eventhalls/venues/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from .models import *
# Create your views here.

@login_required
def home(request):
    return render(request, 'venue-details.html')

@login_required
def general_information(request):
    linked_venuedetail = VenueDetail.objects.filter(venue=request.user.venue).exists()
    linked_dance = DanceFloor.objects.filter(venue=request.user.venue).exists()
    if linked_venuedetail and linked_dance:
        return redirect('venues:edit-general-information')
    venue_detail_form = VenueDetailForm(request.POST or None)
    dance_floor_form = DanceFloorForm(request.POST or None)
    venue_detail_form_2 = VenueDetailForm2(request.POST or None)
    forms = [venue_detail_form, dance_floor_form, venue_detail_form_2]
    if request.method=='POST':
        if venue_detail_form.is_valid() and dance_floor_form.is_valid() and venue_detail_form_2.is_valid():
            for form in forms:
                obj = form.save(commit=False)
                obj.venue = request.user.venue
                obj.save()
            return redirect('venues:venues_home')
    return render(request, 'general-information.html', {'VenueDetailForm':venue_detail_form, 
    'DanceFloorForm':dance_floor_form, 'VenueDetailForm2' : venue_detail_form_2})


@login_required
def edit_general_information(request):
    linked_venuedetail = VenueDetail.objects.filter(venue=request.user.venue).exists()
    linked_dance = DanceFloor.objects.filter(venue=request.user.venue).exists()
    if not linked_dance or not linked_venuedetail:
        return redirect('venues:general-information')
    venue_detail_form = VenueDetailForm(request.POST or None, instance=request.user.venue.venuedetail)
    dance_floor_form = DanceFloorForm(request.POST or None, instance=request.user.venue.dancefloor)
    venue_detail_form_2 = VenueDetailForm2(request.POST or None, instance=request.user.venue.venuedetail)
    forms = [venue_detail_form, dance_floor_form, venue_detail_form_2]
    if request.method=='POST':
        if venue_detail_form.is_valid() and dance_floor_form.is_valid() and venue_detail_form_2.is_valid():
            for form in forms:
                obj = form.save(commit=False)
                obj.venue = request.user.venue
                obj.save()
            return redirect('venues:venues_home')
    return render(request, 'general-information.html', {'VenueDetailForm':venue_detail_form, 
    'DanceFloorForm':dance_floor_form, 'VenueDetailForm2' : venue_detail_form_2})

@login_required
def prewedding_prep(request):
    linked_tasting = Tasting.objects.filter(venue=request.user.venue).exists()
    linked_rehearsal = Rehearsal.objects.filter(venue=request.user.venue).exists()
    linked_arrival_setup = ArrivalSetUp.objects.filter(venue=request.user.venue).exists()
    if linked_tasting and linked_rehearsal and linked_arrival_setup:
        return redirect('venues:edit-prewedding-prep')
    tasting_form = TastingForm(request.POST or None)
    rehearsal_form = RehearsalForm(request.POST or None)
    arrival_setup_form = ArrivalSetUpForm(request.POST or None)
    forms = [tasting_form, rehearsal_form, arrival_setup_form]
    if request.method == 'POST':
        if tasting_form.is_valid() and rehearsal_form.is_valid() and arrival_setup_form.is_valid():
            for form in forms:
                obj = form.save(commit=False)
                obj.venue = request.user.venue
                obj.save()
            return redirect('venues:venues_home')
    return render(request, 'prewedding-preparation.html', {'TastingForm' : tasting_form,
    'RehearsalForm': rehearsal_form, 'ArrivalSetUpForm' : arrival_setup_form})

@login_required
def edit_prewedding_prep(request):
    linked_tasting = Tasting.objects.filter(venue=request.user.venue).exists()
    linked_rehearsal = Rehearsal.objects.filter(venue=request.user.venue).exists()
    linked_arrival_setup = ArrivalSetUp.objects.filter(venue=request.user.venue).exists()
    if not linked_tasting or not linked_rehearsal or not linked_arrival_setup:
        return redirect('venues:prewedding-prep')
    tasting_form = TastingForm(request.POST or None, instance=request.user.venue.tasting)
    rehearsal_form = RehearsalForm(request.POST or None, instance=request.user.venue.rehearsal)
    arrival_setup_form = ArrivalSetUpForm(request.POST or None, instance=request.user.venue.arrivalsetup)
    forms = [tasting_form, rehearsal_form, arrival_setup_form]
    if request.method == 'POST':
        if tasting_form.is_valid() and rehearsal_form.is_valid() and arrival_setup_form.is_valid():
            for form in forms:
                obj = form.save(commit=False)
                obj.venue = request.user.venue
                obj.save()
            return redirect('venues:venues_home')
    return render(request, 'prewedding-preparation.html', {'TastingForm' : tasting_form,
    'RehearsalForm': rehearsal_form, 'ArrivalSetUpForm' : arrival_setup_form})

@login_required
def decorations(request):
    linked_flower = Flower.objects.filter(venue=request.user.venue).exists()
    linked_decoration = Decoration.objects.filter(venue=request.user.venue).exists()
    linked_centerpiece = CenterPiece.objects.filter(venue=request.user.venue).exists()
    if linked_flower and linked_decoration and linked_centerpiece:
        return redirect('venues:edit-decorations')
    decoration_form = DecorationForm(request.POST or None)
    centerpiece_form = CenterPieceForm(request.POST or None)
    flower_form = FlowerForm(request.POST or None)
    forms = [decoration_form, centerpiece_form, flower_form]
    if request.method == 'POST':
        if decoration_form.is_valid() and centerpiece_form.is_valid() and flower_form.is_valid():
            for form in forms:
                obj = form.save(commit=False)
                obj.venue = request.user.venue
                obj.save()
            return redirect('venues:venues_home')
    return render(request, 'decorations.html', {'DecorationForm':decoration_form, 'CenterPieceForm' : centerpiece_form,
    'FlowerForm' : flower_form})

@login_required
def edit_decorations(request):
    linked_flower = Flower.objects.filter(venue=request.user.venue).exists()
    linked_decoration = Decoration.objects.filter(venue=request.user.venue).exists()
    linked_centerpiece = CenterPiece.objects.filter(venue=request.user.venue).exists()
    if not linked_flower or not linked_decoration or not linked_centerpiece:
        return redirect('venues:decorations')
    decoration_form = DecorationForm(request.POST or None, instance=request.user.venue.decoration)
    centerpiece_form = CenterPieceForm(request.POST or None, instance=request.user.venue.centerpiece)
    flower_form = FlowerForm(request.POST or None, instance=request.user.venue.flower)
    forms = [decoration_form, centerpiece_form, flower_form]
    if request.method == 'POST':
        if decoration_form.is_valid() and centerpiece_form.is_valid() and flower_form.is_valid():
            for form in forms:
                obj = form.save(commit=False)
                obj.venue = request.user.venue
                obj.save()
            return redirect('venues:venues_home')
    return render(request, 'decorations.html', {'DecorationForm':decoration_form, 'CenterPieceForm' : centerpiece_form,
    'FlowerForm' : flower_form})

@login_required
def additional_information(request):
    if AdditionalInformation.objects.filter(venue=request.user.venue).exists():
        return redirect('venues:edit-additional-information')
    additional_information = AdditionalInformationForm(request.POST or None)
    if request.method == 'POST':
        if additional_information.is_valid():
            obj = additional_information.save(commit=False)
            obj.venue = request.user.venue
            obj.save()
        return redirect('venues:venues_home')
    return render(request, 'additional-information.html', {'AdditionalInformationForm' : additional_information})

@login_required
def edit_additional_information(request):
    if not AdditionalInformation.objects.filter(venue=request.user.venue).exists():
        return redirect('venues:additional-information')
    additional_information = AdditionalInformationForm(request.POST or None, instance=request.user.venue.additionalinformation)
    if request.method == 'POST':
        if additional_information.is_valid():
            obj = additional_information.save(commit=False)
            obj.venue = request.user.venue
            obj.save()
        return redirect('venues:venues_home')
    return render(request, 'additional-information.html', {'AdditionalInformationForm' : additional_information})

@login_required
def dietary_options(request):
    if DietaryOption.objects.filter(venue=request.user.venue).exists():
        return redirect('venues:edit-dietary-option')
    dietary_option_form = DietaryOptionForm(request.POST or None)
    if request.method == 'POST':
        if dietary_option_form.is_valid():
            obj = dietary_option_form.save(commit=False)
            obj.venue = request.user.venue
            obj.save()
        return redirect('venues:venues_home')
    return render(request, 'dietary-option.html', {'DietaryOptionForm' : dietary_option_form})

@login_required
def edit_dietary_options(request):
    if not DietaryOption.objects.filter(venue=request.user.venue).exists():
        return redirect('venues:dietary-options')
    dietary_option_form = DietaryOptionForm(request.POST or None, instance=request.user.venue.dietaryoption)
    if request.method == 'POST':
        if dietary_option_form.is_valid():
            obj = dietary_option_form.save(commit=False)
            obj.venue = request.user.venue
            obj.save()
        return redirect('venues:venues_home')
    return render(request, 'dietary-option.html', {'DietaryOptionForm' : dietary_option_form})


@login_required

Wedding Halls/eventhalls/venues/templates/accommodations-and-parking.html
{% extends 'base.html' %}

{% block content %}
<form method=POST>
    {% csrf_token %}

    <table>
        {{OvernightForm}}
        {{ParkingForm}}
    </table>
    <button type="submit">Submit</button>
</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/additional-information.html
{% extends 'base.html' %}

{% block content %}
    
    <form method=POST>
        {% csrf_token %}
        
        <table>
            {{AdditionalInformationForm}}
        </table>
        <button type="submit">Submit</button>
    </form>

    <br>
    <a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/ceremony-and-reception.html
{% extends 'base.html' %}

{% block content %}

<form method=POST>
{% csrf_token %}

<h2>Ceremony and Reception Options</h2>

<form method=POST>
    {% csrf_token %}
    
    <table>
        {{IndoorOptionsForm}}
        {{OutdoorOptionsForm}}
    </table>
    <button type="submit">Submit</button>
</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/decorations.html
{% extends 'base.html' %}

{% block content %}
<form method=POST>
    {% csrf_token %}

    <h2>Decorations</h2>
    <table>
        {{DecorationForm}}
    </table>
    <br>

    <h2>Centerpieces</h2>
    <table>
        {{CenterPieceForm}}
    </table>
    <br>

    <h2>Floral Arrangements</h2>
    <table>
        {{FlowerForm}}
    </table>

    <button type="submit">Submit</button>
</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
    {% endblock %}

Wedding Halls/eventhalls/venues/templates/dietary-option.html
{% extends 'base.html' %}

{% block content %}

<h4>Dietary Options</h4>

<form method=POST>
    {% csrf_token %}
        

    <table>
        {{DietaryOptionForm}}
    </table>
    
    <button type="submit" style="width: 80px">Submit</button>

</form>
<br>
    <a href="{% url 'venues:food-and-drink' %}">Go Back</a>

{% endblock %}

Wedding Halls/eventhalls/venues/templates/drink-options.html
{% extends 'base.html' %}

{% block content %}

<form method=POST>
{% csrf_token %}


<h4>Drink Options</h4>
<a href="{% url 'venues:current-drink-pricing' %}">See Current Drink Option Pricing</a><br>


<form class="form-horizontal" method="POST" action="">
  {% csrf_token %}

  <table>
  {{DrinkOptionForm}}
</table>

  {{ formset.management_form }}
<div id="form_set">
  {% for form in formset.forms %}
      <table class='no_error'>
          {{ form }}
      </table>
  {% endfor %}
</div>
<input type="button" value="Add More" id="add_more">
<div id="empty_form" style="display:none">
  <table class='no_error'>
      {{formset.empty_form }}
  </table>
</div>
<br><br>
<button type="submit">Submit</button>



  <script type="text/javascript">
      $('#add_more').click(function() {
      var form_idx = $('#id_form-TOTAL_FORMS').val();
      $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
      $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
  });
  </script>





</form>





<br>

<a href="{% url 'venues:food-and-drink' %}">Go Back</a>

{% endblock %}

Wedding Halls/eventhalls/venues/templates/food-and-drink.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center;">
    <h1>Food and Drink Options</h1>

    <h3>Drink Options</h3>
    <a href="{% url 'venues:drink-options' %}">Set Venue Drink Pricing</a><br>
    <a href="{% url 'venues:current-drink-pricing' %}">See Current Drink Pricing</a><br>
    <br>

    <h3>Dietary Options Offered</h3>
    <a href="{% url 'venues:dietary-option' %}">Select Dietary Options Offered</a><br>
    <br>


    <h3>Menu Options</h3>
    <a href="{% url 'venues:food-option' %}">Set Venue Meal Pricing</a><br>
    <a href="{% url 'venues:current-menu-pricing' %}">See Current Meal Pricing</a><br>



<br>
    <a href="{% url 'venues:venues_home' %}">Go Back</a>
</div>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/general-information.html
{% extends 'base.html' %}

{% block content %}

<form method=POST>
{% csrf_token %}

<h2>General Information</h2>
<table>
    {{VenueDetailForm}}
    {{DanceFloorForm}}
    {{VenueDetailForm2}}
</table>


<button type="submit">Submit</button>

</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/payment-options.html
{% extends 'base.html' %}

{% block content %}
<form method=POST>
    {% csrf_token %}

    <table>
        {{PaymentMethodForm}}
        {{PaymentPlanForm}}

    </table>
    <button type="submit">Submit</button>
</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/photography.html
{% extends 'base.html' %}

{% block content %}
<form method=POST>
    {% csrf_token %}
    <table>
        {{PhotoVideoForm}}
    </table>
    <button type="submit">Submit</button>
</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/staffing-options.html
{% extends 'base.html' %}

{% block content %}

<h3>Staffing Options</h3>

<form method=POST>
    {% csrf_token %}


    {{ formset.management_form }}
    <div id="form_set">
      {% for form in formset.forms %}
          <table class='no_error'>
              {{ form }}
          </table>
      {% endfor %}
    </div>
    <input type="button" value="Add More" id="add_more">
    <div id="empty_form" style="display:none">
      <table class='no_error mt-4'>
          {{formset.empty_form }}
      </table>
    </div>
    <br><br>
    <button type="submit">Submit</button>

    <script type="text/javascript">
        $('#add_more').click(function() {
        var form_idx = $('#id_form-TOTAL_FORMS').val();
        $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
        $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });
    </script>

</form>

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/venue-details.html
{% extends 'base.html' %}

{% block content %}
Hello {{User.first_name}},<br>
Below you can set the details for {{Venue.hall_name}}<br>

<a href="{% url 'venues:general-information' %}">General Information</a><br>
<a href="{% url 'venues:prewedding-prep' %}">Pre-Wedding Preparation</a><br>
<a href="{% url 'venues:food-and-drink' %}">Food and Drink Options</a><br>
<a href="{% url 'venues:wedding-cake' %}">Wedding Cake Options</a><br>
<a href="{% url 'venues:ceremony-and-reception' %}">Ceremony and Reception</a><br>
<a href="{% url 'venues:decorations' %}">Decorations and Floral Arrangements</a><br>
<a href="{% url 'venues:staffing' %}">Staffing Options</a><br>
<a href="{% url 'venues:photography' %}">Photography and Videography Options</a><br>
<a href="{% url 'venues:accommodations-and-parking' %}">Accommodations and Parking</a><br>
<a href="{% url 'venues:additional-information' %}">Additional Information</a><br>
<a href="{% url 'venues:payment-options' %}">Payment Options and Details</a><br>
<a href="{% url 'venues:venue-images' %}">Venue Pictures</a><br>
<a href="{% url 'venues:contact-info' %}">Contact Information</a><br>

{% endblock %}

Wedding Halls/eventhalls/venues/templates/venue-images.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{VenueImageForm}}

<button type="submit">Submit</button>
</form>

{% for image in request.user.venue.venueimage_set.all %}
<img src="{{ image.image.url }}" alt='imagebroken'>
<a class="btn btn-danger btn-sm" href="{% url 'venues:delete-image' image.id %}">Delete</a>
{% endfor %}

<br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}

Wedding Halls/eventhalls/venues/templates/wedding-cake.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <table>
    {{WeddingCakeForm}}
    </table>

    {{ formset.management_form }}
    <div id="form_set">
      {% for form in formset.forms %}
          <table class='no_error'>
              {{ form }}
          </table>
      {% endfor %}
    </div>
    <input type="button" value="Add More" id="add_more">
    <div id="empty_form" style="display:none">
      <table class='no_error'>
          {{formset.empty_form }}
      </table>
    </div>
    <br><br>
    <button type="submit">Submit</button>
    
    
    
      <script type="text/javascript">
          $('#add_more').click(function() {
          var form_idx = $('#id_form-TOTAL_FORMS').val();
          $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
          $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
      });
      </script>
  
    
    </form>

  <br>
    <a href="{% url 'venues:current-cake-details' %}">See Current Wedding Cake Details</a>

<br><br>
<a href="{% url 'venues:venues_home' %}">Go Back</a>
{% endblock %}