Wedding Halls/eventhalls/customers/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customers'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_bar, name='search'),
    path('show/<slug:venue_slug>', views.show_venue, name='show-venue'),
    path('menu-details/<slug:venue_slug>', views.show_food, name='show-food'),
    path('drink-details/<slug:venue_slug>', views.show_drink, name='show-drink'),
    path('accommodations-and-parking/<slug:venue_slug>', views.show_accommodations_and_parking, name='show-accommodations'),
    path('ceremony-and-reception/<slug:venue_slug>', views.show_ceremony_and_reception, name='show-ceremony'),
    path('decoration-and-flower-arrangements/<slug:venue_slug>', views.show_decorations, name='show-decorations'),
    path('staffing-information/<slug:venue_slug>', views.show_staffing, name='show-staffing'),
    path('payment-information/<slug:venue_slug>', views.show_payment, name='show-payment'),
    path('prewedding-prep/<slug:venue_slug>', views.prewedding_prep, name='show-prewedding-prep'),
    path('contact-inforamtion/<slug:venue_slug>', views.show_contact_information, name='show-contact-information'),
    path('additional-details/<slug:venue_slug>', views.show_additional_details, name='show-additional-details'),
    path('photography-and-videography/<slug:venue_slug>', views.show_photography, name='show-photography'),
    path('wedding-cake/<slug:venue_slug>', views.show_wedding_cake, name='show-wedding-cake'),
]

Wedding Halls/eventhalls/eventhalls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('venues/', include('venues.urls'), name='venues-app'),
    path('customers/', include('customers.urls'), name='customers-app'),
    path('', include('main.urls')),
    path('messages/', include('messages_app.urls'), name='messages-app'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Wedding Halls/eventhalls/main/urls.py
from django.urls import include, path
from . import views



urlpatterns = [
    path('', views.main, name = 'main'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact-us/', views.contact_us, name='contact-us')
]

Wedding Halls/eventhalls/venues/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'venues'

urlpatterns = [
    path('', views.home, name='venues_home'),
    path('general-information/', views.general_information, name='general-information'),
    path('edit-general-information/', views.edit_general_information, name='edit-general-information'),
    path('prewedding-preparation/', views.prewedding_prep, name='prewedding-prep'),
    path('edit-prewedding-preparation/', views.edit_prewedding_prep, name='edit-prewedding-prep'),
    path('food-and-drink/', views.food_and_drink, name='food-and-drink'),
    path('drink-options/', views.add_drink_options, name='drink-options'),
    path('dietary-option/', views.dietary_options, name='dietary-option'),
    path('menu-options/', views.add_food_option, name='food-option'),
    path('current-menu-pricing/', views.show_food_pricing, name='current-menu-pricing'),
    path('edit-dietary-option/', views.edit_dietary_options, name='edit-dietary-option'),
    path('ceremony-and-reception/', views.ceremony_and_reception, name='ceremony-and-reception'),
    path('edit-ceremony-and-reception/', views.edit_ceremony_and_reception, name='edit-ceremony-and-reception'),
    path('staffing/', views.staffing, name='staffing'),
    path('accommodations-and-parking/', views.accommodations_and_parking, name='accommodations-and-parking'),
    path('edit-accommodations-and-parking/', views.edit_accommodations_and_parking, name='edit-accommodations-and-parking'),
    path('payment-options/', views.payment_options, name='payment-options'),
    path('edit-payment-options/', views.edit_payment_options, name='edit-payment-options'),
    path('contact-info/', views.contact_info, name='contact-info'),
    path('edit-contact-info/', views.edit_contact_info, name='edit-contact-info'),
    path('decorations/', views.decorations, name='decorations'),
    path('edit-decorations/', views.edit_decorations, name='edit-decorations'),
    path('additional-information/', views.additional_information, name='additional-information'),
    path('edit-additional-information/', views.edit_additional_information, name='edit-additional-information'),
    path('venue-pictures/', views.venue_images, name='venue-images'),
    path('delete-venue-pictures/<int:id>', views.delete_image, name='delete-image'),
    path('current-drink-pricing/', views.show_drink_pricing, name='current-drink-pricing'),
    path('wedding-cake/', views.wedding_cake, name='wedding-cake'),
    path('current-wedding-cake-details/', views.show_wedding_cake, name='current-cake-details'),
    path('photography-and-videography/', views.photography, name='photography'),
    path('edit-photography-and-videography/', views.edit_photography, name='edit-photography')
]

Wedding Halls/eventhalls/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

Wedding Halls/eventhalls/main/views.py
from django.shortcuts import render, redirect

# Create your views here.

def main(request): 
    if request.user.is_authenticated:
        return redirect('router')   
    else:
        return render(request, 'main.html')

def contact_us(request):
    return render(request, 'contact-us.html')

Wedding Halls/eventhalls/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <style>
        input.form-control { width: 300px!important; }
    </style>
    <link rel="stylesheet" href="{% static 'main_style.css' %}">
</head>
<body>
    
    {% if user.venue %}
        {% include 'venues-navbar.html' %}
    {% elif user.customer %}
        {% include 'customer-navbar.html' %}
    {% else %}
        {% include 'main_navbar.html' %}
    {% endif %}
    

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

</body>
</html>

Wedding Halls/eventhalls/main/templates/contact-us.html
{% extends 'base.html' %}

{% block content %}

<h1 style='text-align: center;'>Contact Us</h1>
<br><br>

<p style='text-align: center;'>Derech Menachem Begin 48 <br>Tel Aviv, Israel </p>
<br>
<p style='text-align: center;'>Phone: +972-58-578-5700</p>
<br>

<p style='text-align: center;'>Email: Goldstein.ty@gmail.com</p>

{% endblock %}

Wedding Halls/eventhalls/main/templates/customer-navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="https://i.pinimg.com/originals/92/85/c4/9285c4e6719a6e361a5d1e474b56dfb5.jpg" class="navbar-brand" href="#" style="width:30px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'customers:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#">Search <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <li class="nav-item active">
            <a class="nav-link" href="#">Messages <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'contact-us' %}">Contact Us <span class="sr-only">(current)</span></a>
          </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">Logout <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form method='POST' action='{% url "customers:search" %}' class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" name="customer_search_bar" placeholder="Search by Venue or Zipcode" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

Wedding Halls/eventhalls/main/templates/footer.html
<div class="footer">
    <div>
        Menachem Begin 48 <br>
        Tel Aviv, Israel
    </div>
    <div>
        <a href="{% url 'contact-us' %}">Contact Us</a><br>
        <a href="#">Privacy Policy</a><br>
        <a href="#">Terms of Use</a><br>     
    </div>
</div>
<p class="footer">© 2020 All Rights Reserved</p>

Wedding Halls/eventhalls/main/templates/main.html
{% extends 'base.html' %}

{% block content %}

{% include 'main_jumbo.html' %}

<h1 style="text-align: center;">HOW IT WORKS</h1>

<div class="main_content">
    <div class="content_box";">
        Search through thousands of venues for the perfect place by location, price, style, capacity and more.
    </div>
    <div class="content_box">
        Search for available dates and customize your ideal wedding based on what you want, your budget, and your guest count.
    </div>

</div>


{% endblock %}

Wedding Halls/eventhalls/main/templates/main_jumbo.html
<div class="jumbotron" style="height: 500px;">
    <div style="padding-top: 100px;">
        <h1 class="display-4" style="text-align: center;">Find The Perfect Venue For Your Perfect Day</h1>
        <p class="lead" style="text-align: center;">Browse and Price Out Thousands of Venues.</p>
    
        <form class="form-inline my-2 my-lg-0" style="justify-content: center;">
            <input class="form-control mr-sm-2" type="search" style="width: 450px!important; text-align: center;" placeholder="Search by Venue or Location" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Find a Venue</button>
        </form>
    </div>
  </div>

Wedding Halls/eventhalls/main/templates/main_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img src="https://i.pinimg.com/originals/92/85/c4/9285c4e6719a6e361a5d1e474b56dfb5.jpg" class="navbar-brand" href="#" style="width:30px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/">Browse Venues <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="http://127.0.0.1:8000/">Blog <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'customer-signup' %}">New User <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'venue-signup' %}">Join as a Venue <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search by Venue or Location" aria-label="Search">
        <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
      </form>
    </div>
  </nav>

Wedding Halls/eventhalls/main/templates/venues-navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <img src="https://i.pinimg.com/originals/92/85/c4/9285c4e6719a6e361a5d1e474b56dfb5.jpg" class="navbar-brand" href="#" style="width:30px">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'venues:venues_home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">View Your Page <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
            Edit Venue Details
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a href="{% url 'venues:general-information' %}">General Information</a><br>
            <a href="{% url 'venues:prewedding-prep' %}">Pre-Wedding Preparation</a><br>
            <a href="{% url 'venues:food-and-drink' %}">Food and Drink Options</a><br>
            <a href="{% url 'venues:ceremony-and-reception' %}">Ceremony and Reception</a><br>
            <a href="{% url 'venues:decorations' %}">Decorations and Floral Arrangements</a><br>
            <a href="{% url 'venues:staffing' %}">Staffing Options</a><br>
            <a href="{% url 'venues:accommodations-and-parking' %}">Accommodations and Parking</a><br>
            <a href="{% url 'venues:additional-information' %}">Additional Information</a><br>
            <a href="{% url 'venues:payment-options' %}">Payment Options and Details</a><br>
            <a href="{% url 'venues:venue-images' %}">Venue Pictures</a><br>
            <a href="{% url 'venues:contact-info' %}">Contact Information</a><br>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Messages <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'contact-us' %}">Contact Us <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'logout' %}">Log Out <span class="sr-only">(current)</span></a>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>