Wedding Halls/eventhalls/customers/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customers'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_bar, name='search'),
    path('show/<slug:venue_slug>', views.show_venue, name='show-venue'),
    path('menu-details/<slug:venue_slug>', views.show_food, name='show-food'),
    path('drink-details/<slug:venue_slug>', views.show_drink, name='show-drink'),
    path('accommodations-and-parking/<slug:venue_slug>', views.show_accommodations_and_parking, name='show-accommodations'),
    path('ceremony-and-reception/<slug:venue_slug>', views.show_ceremony_and_reception, name='show-ceremony'),
    path('decoration-and-flower-arrangements/<slug:venue_slug>', views.show_decorations, name='show-decorations'),
    path('staffing-information/<slug:venue_slug>', views.show_staffing, name='show-staffing'),
    path('payment-information/<slug:venue_slug>', views.show_payment, name='show-payment'),
    path('prewedding-prep/<slug:venue_slug>', views.prewedding_prep, name='show-prewedding-prep'),
    path('contact-inforamtion/<slug:venue_slug>', views.show_contact_information, name='show-contact-information'),
    path('additional-details/<slug:venue_slug>', views.show_additional_details, name='show-additional-details'),
    path('photography-and-videography/<slug:venue_slug>', views.show_photography, name='show-photography'),
    path('wedding-cake/<slug:venue_slug>', views.show_wedding_cake, name='show-wedding-cake'),
]

Wedding Halls/eventhalls/eventhalls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('venues/', include('venues.urls'), name='venues-app'),
    path('customers/', include('customers.urls'), name='customers-app'),
    path('', include('main.urls')),
    path('messages/', include('messages_app.urls'), name='messages-app'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Wedding Halls/eventhalls/main/urls.py
from django.urls import include, path
from . import views



urlpatterns = [
    path('', views.main, name = 'main'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contact-us/', views.contact_us, name='contact-us')
]

Wedding Halls/eventhalls/customers/models.py
from django.db import models

# Create your models here.

Wedding Halls/eventhalls/venues/models.py
from django.db import models
from accounts.models import Venue

# Create your models here.
BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

class VenueDetail(models.Model):
    max_guests = models.IntegerField(null=True, blank=True)
    min_guests = models.IntegerField(null=True, blank=True)
    recommended_tip = models.IntegerField(null=True, blank=True)
    outside_catering = models.BooleanField(choices=BOOL_CHOICES, null=True, blank=True)
    venue_only_price = models.IntegerField(blank=True, null = True)
    deposit_fee = models.IntegerField(null=True, blank=True)
    non_refundable_percent = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE, related_name='venuedetail')

class Kosher(models.Model):
    glatt = models.BooleanField(choices=BOOL_CHOICES)
    beit_yoseph = models.BooleanField(choices=BOOL_CHOICES)
    chalav_yisrael = models.BooleanField(choices=BOOL_CHOICES)
    kemach_yisrael = models.BooleanField(choices=BOOL_CHOICES)
    rabbinical_supervision = models.CharField(max_length=150, choices=BOOL_CHOICES)
    dietary = models.OneToOneField('DietaryOption', on_delete=models.CASCADE)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class JewishWedding(models.Model):
    seperate_seating_option = models.BooleanField(choices=BOOL_CHOICES)
    seperate_dancing_option = models.BooleanField(choices=BOOL_CHOICES)
    ichud_room = models.BooleanField(choices=BOOL_CHOICES)
    bride_reception_room = models.BooleanField(choices=BOOL_CHOICES)
    groom_ketubah_room = models.BooleanField(choices=BOOL_CHOICES)
    jewish = models.OneToOneField(Kosher, on_delete=models.CASCADE)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class SeaFood(models.Model):
    lobster = models.BooleanField()
    crab = models.BooleanField()
    shrimp = models.BooleanField()
    oysters = models.BooleanField()
    sea_food_package = models.BooleanField()
    pricing = models.ManyToManyField('Pricing')
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class DietaryOption(models.Model):
    vegitarian = models.BooleanField(choices=BOOL_CHOICES)
    vegan = models.BooleanField(choices=BOOL_CHOICES)
    gluten_free = models.BooleanField(choices=BOOL_CHOICES)
    lactose_free = models.BooleanField(choices=BOOL_CHOICES)
    halal = models.BooleanField(choices=BOOL_CHOICES)
    kosheroption = models.BooleanField(choices=BOOL_CHOICES)
    sea_food = models.BooleanField(choices=BOOL_CHOICES)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class FoodOption(models.Model):
    MEAL_CHOICES = ((True, 'Sit Down'), (False, 'Buffet'))
    meal_option = models.BooleanField(choices=MEAL_CHOICES)
    name_of_food = models.CharField(max_length=50)
    description_of_food = models.CharField(max_length=250)
    pricing = models.ManyToManyField('Pricing')
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    
class DrinkOption(models.Model):
    DRINK_CHOICES = (('full_open_bar','Full Open Bar'), ('bottom_shelf', 'Bottom Shelf Only'),
    ('wine_and_beer','Wine and Beer'), ('wine_only','Wine Only'), ('beer_only','Beer Only'))
    drink_options = models.CharField(max_length=30, choices=DRINK_CHOICES,)
    pricing = models.ManyToManyField('Pricing')
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)

class WeddingCake(models.Model):
    CAKE_CHOICES = (('two_layer','Two Layer Cake'), ('three_layer','Three Layer Cake'), ('four_layer','Four Layer Cake'),('five_layer','Five Layer Cake'))
    cake_option = models.CharField(max_length=50, choices=CAKE_CHOICES,)
    pricing = models.ManyToManyField('Pricing')
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE, related_name='cakes')

class Tasting(models.Model):
    tastings_offered = models.BooleanField(choices=BOOL_CHOICES)
    tasting_price = models.IntegerField(null=True, blank=True)
    pricing = models.ManyToManyField('Pricing')
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class CuttingTheCakeFee(models.Model):
    cake_cutting_fee = models.BooleanField(choices=BOOL_CHOICES)
    fee = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)
    
class CorkFee(models.Model):
    corkage_fee = models.BooleanField(choices=BOOL_CHOICES)
    fee = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class ClosedBottleFee(models.Model):
    closed_bottle_fee = models.BooleanField(choices=BOOL_CHOICES)
    fee = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class Staff(models.Model):
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    number_of_guests = models.IntegerField()
    number_of_waiters = models.IntegerField()
    number_of_bartenders = models.IntegerField()
    number_of_other_staff = models.IntegerField()

class CenterPiece(models.Model):
    provide_centerpieces = models.BooleanField(choices=BOOL_CHOICES)
    basic_pricing = models.IntegerField(null=True, blank=True)
    custom_design = models.BooleanField(choices=BOOL_CHOICES)
    custom_pricing = models.IntegerField(null=True, blank=True)
    outside_centerpieces_allowed = models.BooleanField(choices=BOOL_CHOICES)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class DanceFloor(models.Model):
    max_capacity = models.IntegerField()
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class PaymentMethod(models.Model):
    accept_check = models.BooleanField(choices=BOOL_CHOICES)
    accept_credit_card = models.BooleanField(choices=BOOL_CHOICES)
    wire_transfer = models.BooleanField(choices=BOOL_CHOICES)
    cash_only = models.BooleanField(choices=BOOL_CHOICES)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class PaymentPlan(models.Model):
    payment_plan_option = models.BooleanField(choices=BOOL_CHOICES, null=True, blank=True)
    months = models.IntegerField(null=True, blank=True)
    last_payment_deadline = models.CharField(max_length=50, null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class IndoorOptions(models.Model):
    indoor_reception = models.BooleanField(choices=BOOL_CHOICES)
    indoor_ceremony = models.BooleanField(choices=BOOL_CHOICES)
    indoor_dancing = models.BooleanField(choices=BOOL_CHOICES)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE, related_name='indooroptions')

class OutdoorOptions(models.Model):
    outdoor_reception = models.BooleanField(choices=BOOL_CHOICES)
    outdoor_ceremony = models.BooleanField(choices=BOOL_CHOICES)
    outdoor_dancing = models.BooleanField(choices=BOOL_CHOICES)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE, related_name='outdooroptions')

class RainBackUp(models.Model):
    tents_or_canopies = models.BooleanField(choices=BOOL_CHOICES)
    electric_generator = models.BooleanField(choices=BOOL_CHOICES)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class Overnight(models.Model):
    hotel_partners = models.CharField(max_length=200, null=True, blank=True)
    room_costs = models.IntegerField(null=True, blank=True)
    bulk_rooms_discount = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class Parking(models.Model):
    onsite_parking = models.BooleanField(choices=BOOL_CHOICES)
    car_max = models.IntegerField(null=True, blank=True)
    valet = models.BooleanField(choices=BOOL_CHOICES)
    valet_cost = models.IntegerField(null=True, blank=True)
    parking_cost = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class Rehearsal(models.Model):
    rehearsal_ceremonies = models.BooleanField(choices=BOOL_CHOICES)
    rehearsal_dinners = models.BooleanField(choices=BOOL_CHOICES)
    rehearsal_ceremony_cost = models.IntegerField(null=True, blank=True)
    rehearsal_ceremony_pricing = models.ManyToManyField('Pricing', null=True, blank=True, related_name='rehearsal_ceremony_pricing')
    rehearsal_dinner_cost = models.IntegerField(null=True, blank=True)
    rehearsal_dinner_pricing = models.ManyToManyField('Pricing', related_name='rehearsal_dinner_pricing')
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class InsuranceAndRefund(models.Model):
    cancellation_insurance = models.BooleanField(choices=BOOL_CHOICES)
    insurance_partners = models.CharField(max_length=250, null=True, blank=True)
    cancellation_insurance_cost = models.IntegerField(null=True, blank=True)
    cancellation_policy_days = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class PhotoVideo(models.Model):
    inhouse_photographer = models.BooleanField(choices=BOOL_CHOICES)
    inhouse_videographer = models.BooleanField(choices=BOOL_CHOICES)
    outside_photography = models.BooleanField(choices=BOOL_CHOICES)
    outside_videography = models.BooleanField(choices=BOOL_CHOICES)
    inhouse_photography_cost = models.IntegerField(null=True, blank=True)
    inhouse_video_cost = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class Flower(models.Model):
    outside_florist = models.BooleanField(choices=BOOL_CHOICES)
    custom_floral_design = models.BooleanField(choices=BOOL_CHOICES)
    custom_floral_pricing = models.IntegerField(null=True, blank=True)
    basic_florist_pricing = models.IntegerField(null=True, blank=True)
    venue = models.OneToOneField(Venue, on_delete=models.CASCADE)

class Decoration(models.Model):
    provide_decorations = models.BooleanField(choices=BOOL_CHOICES)
    decorations_pricing = models.IntegerField(null=True, blank=True)
    outside_decorations = models.BooleanField(choices=BOOL_CHOICES)

Wedding Halls/eventhalls/customers/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from venues.filters import VenueFilter
from venues.models import Venue
from django.db.models import Q
from django.views.decorators.http import require_http_methods

# Create your views here.



@login_required
def home(request):
    filter = VenueFilter(request.GET, queryset=Venue.objects.all())
    return render(request, 'customer_welcome.html', {'filter': filter})

@login_required
@require_http_methods(['POST'])
def search_bar(request):
    if request.method=='POST':
        text=request.POST.get('customer_search_bar')
        venues = Venue.objects.filter(Q(hall_name__icontains=text) | Q(zipcode=text))
    return render(request, 'search-results.html', {'venues' : venues})

@login_required
def show_venue(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-venue-main.html', {'venue' : venue})

@login_required
def show_food(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-food.html', {'venue' : venue})

@login_required
def show_drink(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-drink.html', {'venue' : venue})

@login_required
def show_accommodations_and_parking(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-accommodations.html', {'venue' : venue})

@login_required
def show_ceremony_and_reception(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-ceremony-and-reception.html', {'venue' : venue})

@login_required
def show_decorations(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-decorations.html', {'venue' : venue})

@login_required
def show_staffing(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-staffing.html', {'venue' : venue})

@login_required
def show_payment(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-payment.html', {'venue' : venue})

@login_required
def prewedding_prep(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'prewedding-prep.html', {'venue' : venue})

@login_required
def show_contact_information(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-contact-information.html', {'venue' : venue})

@login_required
def show_additional_details(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-additional-details.html', {'venue' : venue})

@login_required
def show_photography(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-photography.html', {'venue' : venue})

@login_required
def show_wedding_cake(request, venue_slug):
    venue = Venue.objects.get(slug=venue_slug)
    return render(request, 'show-wedding-cake.html', {'venue' : venue})

Wedding Halls/eventhalls/customers/templates/customer_welcome.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron"' style="background-image: url(https://blushbanquethall.com/wp-content/uploads/2018/06/wedding-venue-decoration.jpg); width=100%;">
    <h1 class="display-4" style="text-align: center;">The Perfect Wedding Starts With The Perfect Venue!</h1>
    <p class="lead" style="text-align: center;">Start your search below.</p>
    <hr class="my-4">
    
    <form method="GET">
      {% csrf_token %}
      <div class="container">
      <div class='row'>
        <div class='col'>{{filter.form.max_guests.label_tag}} {{filter.form.max_guests}}</div>
        <div class='col'>{{filter.form.city.label_tag}} {{filter.form.city}}</div>
        <div class='col'>{{filter.form.zipcode.label_tag}} {{filter.form.zipcode}}</div>
        </div>
      </div>
  
  <p>
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Advanced Search
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <div class="container">
        <div class='row'>
          <div class='col'>{{filter.form.outside_catering.label_tag}} {{filter.form.outside_catering}}</div>
          <div class='col'>{{filter.form.outdoor_ceremony.label_tag}} {{filter.form.outdoor_ceremony}}</div>
          <div class='col'>{{filter.form.onsite_parking.label_tag}} {{filter.form.onsite_parking}}</div>
          <div class='col'>{{filter.form.valet.label_tag}} {{filter.form.valet}}</div>
          <div class='col'>{{filter.form.smoking_area.label_tag}} {{filter.form.smoking_area}}</div>
          </div>
        </div>
    </div>
  </div>

    <p class="lead">
      <button type='submit' class="btn btn-primary btn-lg" role="button" style="margin-left: 48%;">Search</button>
    </p>
  </form>
</div>

<div class='row'>
  {% for obj in filter.qs %}
  <div class="card" style="width: 18rem;">
    <img src="{{obj.venueimage_set.first.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{obj.hall_name}}</h5>
      <p class="card-text">{{obj.city}}</p>
      <a href="{% url 'customers:show-venue' obj.slug %}" class="btn btn-primary">View Hall Details</a>
    </div>
  </div>
{% endfor %}
</div>

{% endblock %}

Wedding Halls/eventhalls/customers/templates/prewedding-prep.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<div style="text-align: center;">

<h3>Tastings</h3>
Tastings Offered:&nbsp; {{venue.tasting.tastings_offered |yesno:'Yes,No'}}<br>
Cost for Tasting: &nbsp;{{venue.tasting.tasting_price}}<br>

<br>
<h3>Rehearsals</h3>
Rehearsal Dinner Option: &nbsp;{{venue.rehearsal.rehearsal_dinners |yesno:'Yes,No'}}<br>
Rehearsal Dinner Cost: &nbsp;{{venue.rehearsal.rehearsal_dinner_cost}}<br>
Rehearsal Ceremony Option: &nbsp;{{venue.rehearsal.rehearsal_ceremonies |yesno:'Yes,No'}}<br>
Rehearsal Ceremony Cost:&nbsp; {{venue.rehearsal.rehearsal_ceremony_cost}}<br>

<br>
<h3>Wedding Day Arrival and Set Up</h3>
Prewedding Arrival: &nbsp;{{venue.arrivalsetup.hours_preevent_arrival}} Hours Prior to Wedding<br>
Prewedding Set Up: &nbsp;{{venue.arrivalsetup.hours_preevent_setup}} Hours Prior to Wedding<br>


<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>

</div>
{% endblock %}

Wedding Halls/eventhalls/customers/templates/search-results.html
{% extends 'base.html' %}

{% block content %}

{% for venue in venues %}
    {{venue}}

{% endfor %}

{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-accommodations.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<h3>Onsite Parking Information </h3>

<p>Onsite Parking Available: {{venue.parking.onsite_parking |yesno:'Yes,No'}}</p>
<p>Max Cars in Parking Lot: {{venue.parking.car_max}}</p>
<p>Valet Option Available: {{venue.parking.valet |yesno:'Yes,No' }}</p>
<p>Cost of Valet Service: {{venue.parking.valet_cost}}</p>
<p>Cost of Parking: {{venue.parking.parking.cost}}</p>


<h3>Hotel Partners</h3>

<p>Hotel Partners: {{venue.parking.hotel_partners}}</p>
<p>Average Cost of Rooms {{venue.parking.room_costs}}</p>
<p>Average Bulk Room Discounts {{venue.parking.bulk_rooms_discount}}</p>


<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>

{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-contact-information.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<div style="text-align: center;">

<h3>General Contact Information</h3>
Contact Name:&nbsp; {{venue.generalcontact.contact_person}}<br>
Phone: &nbsp;{{venue.generalcontact.phone}}<br>
Email: &nbsp;{{venue.generalcontact.email}}<br>

<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>

</div>
{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-drink.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<div style="text-align: center;">
    {% for drinkoption in venue.drinkoption_set.all %}
    
        <h2>Prices for {{drinkoption.get_drink_options_display}}</h2>
        {% for pricing in drinkoption.pricing.all %}
        Number of Guests: {{pricing.amount_of_people}}  Cost: {{pricing.cost}}
        <br>
        {% endfor %}
        <br>
    {% endfor %}


<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>

</div>
{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-food.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>




<ul>
    {% for foodoption in venue.foodoption_set.all %}
       <li> Name: &nbsp; {{foodoption.name_of_food}} &nbsp;&nbsp;  
        Description: &nbsp; {{foodoption.description_of_food}}</li>
    
    {% endfor %}
    </ul>



<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>


{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-staffing.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<div style="text-align: center;">
    {% for staffing in venue.staff_set.all %}
    
        Staff for {{staffing.number_of_guests}} Guests<br>
        Number of Waiters: &nbsp;{{staffing.number_of_waiters}}<br>
        Number of Bartenders: &nbsp;{{staffing.number_of_bartenders}}<br>
        Number of Other Staff:&nbsp; {{staffing.number_of_other_staff}}<br>


        <br>
    {% endfor %}



<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>

</div>
{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-venue-main.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<h6>Address</h6>
<p>{{venue.address_line_1}}<br>
{{venue.address_line_2}}<br>
{{venue.city}} {{venue.state}} {{venue.zipcode}}</p>

<p>Max Guests: {{venue.venuedetail.max_guests}}</p>
<p>Min Guests: {{venue.venuedetail.min_guests}}</p>
<p>Dance Floor Capacity: &nbsp; {{venue.dancefloor.max_capacity}}</p>

{% for image in venue.venueimage_set.all %}
<img src="{{ image.image.url }}" alt='imagebroken' style="width: 400px">

{% endfor %}
<br><br>

<a href="{% url 'customers:show-food' venue.slug %}">See Menu and Pricing Information</a><br>
<a href="{% url 'customers:show-drink' venue.slug %}">See Drink Pricing Information</a><br>
<a href="{% url 'customers:show-wedding-cake' venue.slug %}">See Wedding Cake Options</a><br>
<a href="{% url 'customers:show-accommodations' venue.slug %}">See Venue Accommodations and Parking Information</a><br>
<a href="{% url 'customers:show-ceremony' venue.slug %}">See Venue Ceremony and Reception Options </a><br>
<a href="{% url 'customers:show-decorations' venue.slug %}">See Venue Decoration and Flower Options</a><br>
<a href="{% url 'customers:show-photography' venue.slug %}">See Photography and Videography Options</a><br>
<a href="{% url 'customers:show-staffing' venue.slug %}">See Venue Staffing Information</a><br>
<a href="{% url 'customers:show-prewedding-prep' venue.slug %}">See Venue Tastings, Rehearsals and Pre-Wedding Preparation Information</a><br>
<a href="{% url 'customers:show-additional-details' venue.slug %}">See Additional Venue Details</a><br>
<a href="{% url 'customers:show-payment' venue.slug %}">See Venue Payment Information</a><br>
<a href="{% url 'customers:show-contact-information' venue.slug %}">See Venue Contact Information</a><br>


<br>
<a href="#">Go Back to Search Results</a><br>
{% endblock %}

Wedding Halls/eventhalls/customers/templates/show-wedding-cake.html
{% extends 'base.html' %}

{% block content %}

<h1 style="text-align: center;">{{venue.hall_name}}</h1>

<div style="text-align: center;">

    Venue Provides Wedding Cake:&nbsp; {{venue.additionalinformation.provide_wedding_cake}}<br>


    {% for cake in venue.cakes.all %}
    
        <h2>Cake Layers {{cake.get_cake_option_display}}</h2>
        {% for pricing in cake.pricing.all %}
        Number of Guests: {{pricing.amount_of_people}}  Cost: {{pricing.cost}}
        <br>
        {% endfor %}
        <br>
    {% endfor %}


<br>
<a href="{% url 'customers:show-venue' venue.slug %}">Go Back</a><br>

</div>
{% endblock %}